# Generated by Django 2.2 on 2020-12-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(max_length=1)),
                ('y', models.IntegerField(max_length=1)),
                ('face', models.CharField(max_length=10)),
                ('start', models.CharField(max_length=10)),
                ('last_position', models.CharField(max_length=10)),
            ],
        ),
    ]
