# Generated by Django 2.2 on 2020-12-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201219_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='face',
            field=models.IntegerField(),
        ),
    ]
