# Generated by Django 2.2 on 2020-12-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201221_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='start',
            field=models.CharField(default='0,0,90', max_length=10),
        ),
    ]
